### ISSUE TITLE
Consider releasing as a gem?

### ISSUE THREAD

**Issue by scottatron** [gitlabhq/gitlab-ci-runner#113]
Would you consider releasing the runner as a gem?

While it's not hard to install, a simple `gem install gitlab-ci-runner` would be handy.

I'd be happy to submit a PR for this if you're open to it.

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.

**Comment by Razer6** [comment]
There is now an omnibus package for the runner
