### ISSUE TITLE
Init script does not return correct code when service is not running

### ISSUE THREAD

**Issue by canni** [gitlabhq/gitlab-ci-runner#122]
Tools such as SaltStack/Puppet/Chef etc. often relay on call like `service gitlab-ci-runner status` to determine is service is running.

Currently call to `status` always returns code `0` so my conf management is thinking that service is running, and does not require starting, while in reality it's stopped.

maybe doing `exit [ $RUNNERS_RUNNING -gt 0 ]` in status func is good enough?

**Comment by Razer6** [comment]
Closing this since this variable has been removed and hope to be fixed.
