### ISSUE TITLE
gitlab-ci-runner does not build after upgrade

### ISSUE THREAD

**Issue by ovanes** [gitlabhq/gitlab-ci-runner#127]
Just did:
* gitlab 6.7.2 -> 7.6 upgrade
* gitlab-ci 5.0 -> 5.1 -> 5.2 -> 5.3 update
* gitlab-ci-runner -> 5.0.0 upgrade and later master branch upgrade

In Gitlab CI this build just hangs and nothing happens. I tried the steps of the build manually in the gitlab-ci-runner/tmp/projec-N/ directory. Everything works fine.

Executing gitlab-ci-runner manually using:
   
     bundle exec ./bin/runner

produces the message:

    2014-12-20 20:51:25 +0000 | Checking for builds...nothing
    2014-12-20 20:51:30 +0000 | Checking for builds...received
    failed

Can I somewhere lookup what failed?

**Comment by vsizov** [comment]
Do you still have the same problem on new GitLab CI and runner?

**Comment by ovanes** [comment]
I had to delete the runners and configure them again. After that it worked.

**Comment by Razer6** [comment]
Strange. However let's close this here.
