### ISSUE TITLE
Missing project tags

### ISSUE THREAD

**Issue by Jack12816** [gitlabhq/gitlab-ci-runner#134]
Hello,

it looks like some tags are missing for the gitlab-ci-runner. So I can't find the current `5.2.0` tag.
Could you please tag it? This would be relevant for custom Docker builds and stuff like that. :)

**Comment by maxlazio** [comment]
@Jack12816 Thanks for the report, @vsizov will sync the repository :)

**Comment by vsizov** [comment]
updated. Thank you @Jack12816 for the report.

**Comment by Jack12816** [comment]
No problem. :)
