### ISSUE TITLE
Stops, builds forever pending

### ISSUE THREAD

**Issue by PaulBGD** [gitlabhq/gitlab-ci-runner#135]
I have all my builds currently pending. If I go to my runner, it says from the status:
```
root@vps36199:~# service gitlab-ci-runner status
Here is what we have at the moment:
runner is running with PID = 701
```

the builds are assigned to the runner, and the runner is not paused. Rebooting the machine or restarting the runner does not cause it to start again.

However, assigning it to all projects then remove it's assignments makes it start again.

**Comment by vsizov** [comment]
Please provider additional information: version, how did you install it and so on.

**Comment by PaulBGD** [comment]
v5.2.1, and I installed it on Ubuntu using the instructions from the README

**Comment by PaulBGD** [comment]
Going to close this for ya'll since the project is deprecated and the go runner works great.
