### ISSUE TITLE
Unable to clone the build

### ISSUE THREAD

**Issue by ThibaudDauce** [gitlabhq/gitlab-ci-runner#137]
Hi,

I have a Gitlab runner instance and every build failed because it can't clone the repo…

```
cd /home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds && git clone http://gitlab-ci-token:xxxxxx@gitlab.pic/picdata/developpement.git project-1 && cd project-1 && git checkout 80901d0702835f3878d9720b8fce5048f3926f92
Cloning into 'project-1'...
fatal: http://gitlab-ci-token:xxxxxx@gitlab.pic/picdata/developpement.git/info/refs not found: did you run git update-server-info on the server?
cd /home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-1 && git reset --hard && git checkout 80901d0702835f3878d9720b8fce5048f3926f92
/tmp/executor20150422-27207-147ea43: ligne 7 : cd: /home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-1: Aucun fichier ou dossier de ce type
git submodule update --init
You need to run this command from the toplevel of the working tree.
```

Do you have any idea ? I work behind a proxy and I set my no_proxy variable for .pic :
```
# echo $no_proxy 
.pic
```

I didn't replace my token by xxxxxx, the script really try to clone `git clone http://gitlab-ci-token:xxxxxx@gitlab.pic/picdata/developpement.git project-1`

When I try to go to `http://gitlab.pic/picdata/developpement.git/info/refs` with my usual computer, firefox, and my Gitlab login and password, I get : `Not Found`.

I try to go into `/var/opt/gitlab/git-data/repositories/picdata/developpement.git/`and execute `git update-server-info` but I nothing change… 

I don't know what to do…

Thanks

**Comment by AntoineAugusti** [comment]
@ThibaudDauce Fixed?
