### ISSUE TITLE
Programmatically get gitlab ci token

### ISSUE THREAD

**Issue by onaclov2000** [gitlabhq/gitlab-ci-runner#142]
Is there a way to automatically get the gitlab ci token? I am trying to setup an entire environment programmatically, but don't know how to get the token without manually logging in and getting it.

Is this possible?

**Comment by axilleas** [comment]
This repo is deprecated, forward any questions you might have at https://gitlab.com/gitlab-org/gitlab-ci/issues.

I haven't chacked, but maybe there is something in the docs https://gitlab.com/gitlab-org/gitlab-ci/tree/master/doc/api.
