### ISSUE TITLE
Could not locate Gemfile ERROR: Build failed: exit code 1

### ISSUE THREAD

**Issue by kdpuvvadi** [gitlabhq/gitlab-ci-runner#145]
facing problem with CI runner,

```
$ ruby -v
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-linux]
$ which ruby
/usr/local/bin/ruby
$ gem install bundler --no-ri --no-rdoc
Successfully installed bundler-1.13.0
1 gem installed
$ bundle install --jobs $(nproc)  "${FLAGS[@]}"
Could not locate Gemfile
ERROR: Build failed: exit code 1
````

**Comment by ZJvandeWeg** [comment]
This project is [deprecated](https://github.com/gitlabhq/gitlab-ci-runner#gitlab-runner-project-is-deprecated-now-please-use-new-gitlab-runner-written-in-go-previously-named-gitlab-ci-multi-runner-instead)

But even than, you seem to be in the wrong folder or there really is no `Gemfile` there.
