### ISSUE TITLE
Use configurable build path for runners

### ISSUE THREAD

**Issue by caffed** [gitlabhq/gitlab-ci-runner#29]
Can there be an option in the config.yml to all for an optional build path setting?

Example (lib/config.rb):

```ruby
    def builds_dir
      @builds_path = @config['builds_path'] || File.join(ROOT_PATH, 'tmp', 'builds')
    end
```

I host all of these projects internally on one server an use rvm to manage gemsets. 

Carlo

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
